#%RAML 1.0 DataType
(package): Type
(docs-uri): https://docs.commercetools.com/http-api-projects-types.html#type

(javaImport): io.sphere.sdk.models.Reference<com.commercetools.importer.models.Type.Type>
type: Reference
displayName: TypeReference
discriminatorValue: type
properties:
    obj?:
        type: Type
