#%RAML 1.0 DataType
(package): Product

(javaImport): io.sphere.sdk.commands.UpdateAction<Product>
(abstract): true
type: object
displayName: ProductUpdateAction
discriminator: action
properties:
    action:
        type: string