#%RAML 1.0 DataType
(package): Channel
(docs-uri): https://docs.commercetools.com/http-api-projects-channels.html#channel


(javaImport): io.sphere.sdk.models.Reference<com.commercetools.importer.models.Channel.Channel>
displayName: ChannelReference
discriminatorValue: channel
properties:
    obj?:
        type: Channel
