#%RAML 1.0 DataType
(package): Category

(javaImport): io.sphere.sdk.commands.UpdateAction<Category>
(abstract): true
type: object
displayName: CategoryUpdateAction
discriminator: action
properties:
    action:
        type: string